name: Test, build and upload artifact

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    uses: MinestomBrick/.github/.github/workflows/java-gradle-test.yml@main

  pre-release:
    needs: test
    uses: MinestomBrick/.github/.github/workflows/java-gradle-github-release.yml@main