name: Gradle github release

on:
  push:
    tags:
    - '*'
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    uses: GufliOfficial/.github/.github/workflows/java-gradle-test.yml@main

  release:
    needs: test
    uses: GufliOfficial/.github/.github/workflows/java-gradle-github-release.yml@main