name: Gradle github release

on:
  push:
    tags:
    - '*'
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    uses: GufliOfficial/.github/.github/workflows/java-gradle-test.yml@main

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - uses: actions/checkout@v3
        with:
          ref: '${{ steps.get-latest-tag.outputs.tag }}'

      - name: Get current timestamp
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Build with Gradle
        run: './gradlew shadowJar'

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: build/libs/*.jar
          title: '${{ steps.get-latest-tag.outputs.tag }}: Minestom update at ${{ steps.date.outputs.date }}'