name: Gradle github release

on:
  push:
    tags:
    - '*'
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    uses: GufliOfficial/.github/.github/workflows/java-gradle-test.yml@main

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - uses: actions/checkout@v3
        with:
          ref: '${{ steps.get-latest-tag.outputs.tag }}'

      - name: Get current datetime
        id: datetime
        run: echo "::set-output name=datetime::$(date +'%Y-%m-%d %H:%M:%S')"

      - name: Get current datetime in version format
        id: datetimever
        run: echo "::set-output name=datetime::$(date +'%Y%m%d%H%M%S')"

      - name: Build with Gradle
        run: './gradlew shadowJar'

      - name: Rename output file
        run: 'mv build/libs/Brickstom-${{ steps.get-latest-tag.outputs.tag }}.jar build/libs/Brickstom-${{ steps.get-latest-tag.outputs.tag }}-${{ steps.datetimever.outputs.datetimever }}.jar'

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: build/libs/*.jar
          automatic_release_tag: '${{ steps.get-latest-tag.outputs.tag }}'
          title: '${{ steps.get-latest-tag.outputs.tag }}: Build at ${{ steps.datetime.outputs.datetime }}'